version: '3.1'

services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: php
      target: builder
    depends_on:
      - db
    ports:
      - 8000:80
    volumes:
      - ./app:/var/www/html/
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
